version: '3'

services:
 app:
   build: .
   image: solo-gyotaku:latest
   ports:
     - "3000:3000"
   environment:
     PORT: 3000
     K_SERVICE: solo-gyotaku
     K_REVISION: 0
     K_CONFIGURATION: solo-gyotaku
